---
provisioner:
  name: chef_solo
  data_bags_path: test/integration/data_bags

verifier: inspec
suites:
  - name: test
    run_list:
      - recipe[test-cookbook]
      - recipe[resource_from_hash_test::default]
