---
provisioner:
  name: chef_solo
  data_bags_path: test/integration/data_bags
  attributes:
    authorization:
      sudo:
        users:
          - vagrant
          - centos
          - ubuntu
          - fedora

suites:
  - name: test
    run_list:
      - recipe[resource_from_hash_test::default]
