AllCops:
  Include:
    - '**/Berksfile'
    - '**/Cheffile'
  Exclude:
    - '**/metadata.rb'

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Eval:
  Enabled: false

AbcSize:
  Enabled: false
