name             'resource_from_hash'
maintainer       'Oregon State University'
maintainer_email 'systems@osuosl.org'
source_url       'https://github.com/osuosl-cookbooks/resource_from_hash'
issues_url       'https://github.com/osuosl-cookbooks/resource_from_hash/issues'
license          'Apache-2.0'
chef_version     '>= 16.0'
description      'Installs/Configures resource_from_hash'
version          '1.3.0'

supports         'centos', '~> 7.0'
